package com.androidbuilder.agent;

import com.androidbuilder.model.FileOperation;
import com.androidbuilder.model.HermesTaskContract;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Batch validation adjudicates a batch from its OWN operations + the batch manifest only. It does
 * NOT check resource existence: a task runs in an isolated scratch fork that cannot see sibling
 * tasks' resources, so a scratch-tree existence check produces a false "missing R.X" for every
 * legitimate cross-task reference. Resource existence is a whole-tree property and is validated
 * exactly once, by AndroidSourceGuard at merge time on the full canonical tree (the sole authority).
 */
final class BatchValidationPolicy {
    private BatchValidationPolicy() {
    }

    static String review(List<FileOperation> batchOps,
                         List<String> manifestPathsForBatch,
                         HermesTaskContract contract) {
        List<FileOperation> canonicalOps = canonicalOps(batchOps);
        for (FileOperation operation : canonicalOps) {
            if (!"write".equals(operation.action) && !"delete".equals(operation.action)) {
                return "Batch validation: batch operations must be full write or delete; got " + operation.action + " for " + operation.path + ". Resend the complete file content.";
            }
        }
        Set<String> plannedPaths = canonicalPaths(manifestPathsForBatch);
        Set<String> actualPaths = operationPaths(canonicalOps);
        for (String actualPath : actualPaths) {
            // An additive res/** file is a conflict-free resource the batch may need to declare for a
            // referenced-but-not-yet-present resource (any type: drawable, layout, menu, values, ...).
            // Self-healing it in one pass is the desired behavior, not an "unplanned file" to reject;
            // the merge-time guard still rejects a structurally broken or duplicate resource. Other
            // unplanned files (stray Java, etc.) still sprawl and are rejected.
            if (!plannedPaths.contains(actualPath) && !isAdditiveResourceFile(actualPath)) {
                return "Batch validation: batch contained unplanned file " + actualPath + "; regenerate only the requested files.";
            }
        }
        // A batch that omits some planned files is NOT rejected: rejecting the whole batch (incl. the
        // files it DID produce) is all-or-nothing and never converges when a weak model keeps dropping a
        // few files, or when a salvaged-from-truncation batch is necessarily partial. The accepted partial
        // is kept and the still-missing files are regenerated by the caller's carry-forward rounds
        // (ManifestResumePolicy.remainingBatches over the manifest minus accepted). Only structural
        // problems (bad action, unplanned sprawl, preflight API mismatch) still reject the batch.
        return TaskStreamPreflight.review(canonicalOps, contract);
    }

    private static List<FileOperation> canonicalOps(List<FileOperation> operations) {
        List<FileOperation> canonical = new ArrayList<>();
        if (operations == null) {
            return canonical;
        }
        for (FileOperation operation : operations) {
            canonical.add(CanonicalPathPolicy.canonicalOperation(operation));
        }
        return canonical;
    }

    private static boolean isAdditiveResourceFile(String path) {
        return path != null && path.startsWith("app/src/main/res/");
    }

    private static Set<String> canonicalPaths(List<String> paths) {
        Set<String> canonical = new LinkedHashSet<>();
        if (paths == null) {
            return canonical;
        }
        for (String path : paths) {
            canonical.add(CanonicalPathPolicy.canonicalize(path));
        }
        return canonical;
    }

    private static Set<String> operationPaths(List<FileOperation> operations) {
        Set<String> paths = new LinkedHashSet<>();
        for (FileOperation operation : operations) {
            paths.add(operation.path);
        }
        return paths;
    }
}
